# .github/workflows/test.yml

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment for each run

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up Python
      with:
        python-version: '3.x' # Use the latest Python 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip # Upgrade pip
        pip install poetry # If you use poetry for dependency management, install it here. If not, just use pip below.
        pip install -e . # Install your package in editable mode, which includes its dependencies
        pip install pytest # Install pytest to run your tests

    - name: Run tests
      run: |
        pytest # Execute pytest. Make sure your tests are in a 'tests' directory as discussed.
